// <auto-generated />
using System;
using DA.AppDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515111232_BatchNoAndIsBarcode")]
    partial class BatchNoAndIsBarcode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DM.DomainModels.Inspection_Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Inspection_Card");
                });

            modelBuilder.Entity("DM.DomainModels.Inspection_Characteristic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("SingleCriteria")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Inspection_Characteristic");
                });

            modelBuilder.Entity("DM.DomainModels.Inspection_Characteristic_Mapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionCardId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("InspectionCardId");

                    b.ToTable("Inspection_Characteristic_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocNum")
                        .HasColumnType("text");

                    b.Property<string>("GroupCode")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBatch")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEnabledForQA")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("LineNum")
                        .HasColumnType("text");

                    b.Property<string>("ManageBatchNumbers")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("U_QACard")
                        .HasColumnType("text");

                    b.Property<string>("UoMGroupEntry")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Inspection_Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CardDescription")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionCardId")
                        .HasColumnType("text");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InspectionCardId");

                    b.HasIndex("ItemId");

                    b.ToTable("Item_Inspection_Card");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Flexibility")
                        .HasColumnType("boolean");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Sample");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Post_Sap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AnalyzedBy")
                        .HasColumnType("text");

                    b.Property<string>("BMR")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("InspectionQuantity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPerformed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPostedToSap")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OverallStatus")
                        .HasColumnType("boolean");

                    b.Property<int?>("QCode")
                        .HasColumnType("integer");

                    b.Property<string>("QId")
                        .HasColumnType("text");

                    b.Property<string>("QType")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportNextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SampleQuantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("SamplesPassedCount")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QId");

                    b.ToTable("Log_Post_Sap");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QA_Cavity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CavityId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCavityPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsToggledOn")
                        .HasColumnType("boolean");

                    b.Property<string>("MouldNo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("QaId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CavityId");

                    b.ToTable("Log_Production_QA_Cavity");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QA_Cavity_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QaCavitySampleId")
                        .HasColumnType("text");

                    b.Property<string>("QaCavitySampleResultId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QaCavitySampleResultId");

                    b.ToTable("Log_Production_QA_Cavity_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QC_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QcSampleId")
                        .HasColumnType("text");

                    b.Property<string>("QcSampleResultId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcSampleResultId");

                    b.ToTable("Log_Production_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Purchase_QC_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QcSampleId")
                        .HasColumnType("text");

                    b.Property<string>("QcSampleResultId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcSampleResultId");

                    b.ToTable("Log_Purchase_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Sampling_Range", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CriticalDefects")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ItemSampleFlexibility")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemSampleId")
                        .HasColumnType("text");

                    b.Property<double?>("LotSizeMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("LotSizeMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("MajorDefects")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinorDefects")
                        .HasColumnType("double precision");

                    b.Property<double?>("SampleQty")
                        .HasColumnType("double precision");

                    b.Property<string>("SamplingRangeId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SamplingRangeId");

                    b.ToTable("Log_Sampling_Range");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AnalyzedBy")
                        .HasColumnType("text");

                    b.Property<string>("BMRLoc")
                        .HasColumnType("text");

                    b.Property<string>("BMRNo")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("BatchNo")
                        .HasColumnType("text");

                    b.Property<string>("CardCode")
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Cavity")
                        .HasColumnType("text");

                    b.Property<double?>("CavityNo")
                        .HasColumnType("double precision");

                    b.Property<double?>("CompletedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CycleTime")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocEntry")
                        .HasColumnType("text");

                    b.Property<string>("DocNo")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("InspectionQuantity")
                        .HasColumnType("double precision");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<string>("InventoryUoM")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBarcodeGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPerformed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPostedToSap")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("ItemWeight")
                        .HasColumnType("text");

                    b.Property<string>("MachineNo")
                        .HasColumnType("text");

                    b.Property<string>("MouldNo")
                        .HasColumnType("text");

                    b.Property<double?>("OpenQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("OperatedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("OverallStatus")
                        .HasColumnType("boolean");

                    b.Property<double?>("PlannedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductionOrderStatus")
                        .HasColumnType("text");

                    b.Property<string>("QcLotNo")
                        .HasColumnType("text");

                    b.Property<double?>("ReceiveQuantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RejectedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportNextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SampleQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Shift")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UoM")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<string>("Warehouse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Production_QA");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCavityPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsToggledOn")
                        .HasColumnType("boolean");

                    b.Property<string>("MouldNo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("QaId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QaId");

                    b.ToTable("Production_QA_Cavity");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CavityId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectionQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("IntCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CavityId");

                    b.ToTable("Production_QA_Cavity_Sample");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QaCavitySampleId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QaCavitySampleId");

                    b.HasIndex("QualitativeInspectionMappingId");

                    b.HasIndex("QualitativeResultId");

                    b.HasIndex("QuantitativeInspectionMappingId");

                    b.ToTable("Production_QA_Cavity_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AnalyzedBy")
                        .HasColumnType("text");

                    b.Property<string>("BMRLoc")
                        .HasColumnType("text");

                    b.Property<string>("BMRNo")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("BatchNo")
                        .HasColumnType("text");

                    b.Property<string>("CardCode")
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<string>("Cavity")
                        .HasColumnType("text");

                    b.Property<double?>("CavityNo")
                        .HasColumnType("double precision");

                    b.Property<double?>("CompletedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CycleTime")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocEntry")
                        .HasColumnType("text");

                    b.Property<string>("DocNo")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("InspectionQuantity")
                        .HasColumnType("double precision");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<string>("InventoryUoM")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBarcodeGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPerformed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPostedToSap")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("ItemWeight")
                        .HasColumnType("text");

                    b.Property<string>("MachineNo")
                        .HasColumnType("text");

                    b.Property<string>("MouldNo")
                        .HasColumnType("text");

                    b.Property<double?>("OpenQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("OperatedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("OverallStatus")
                        .HasColumnType("boolean");

                    b.Property<double?>("PlannedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductionOrderStatus")
                        .HasColumnType("text");

                    b.Property<string>("QcLotNo")
                        .HasColumnType("text");

                    b.Property<double?>("ReceiveQuantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RejectedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportNextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SampleQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Shift")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UoM")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<string>("Warehouse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Production_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectionQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("QcId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcId");

                    b.ToTable("Production_QC_Sample");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QcSampleId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcSampleId");

                    b.HasIndex("QualitativeInspectionMappingId");

                    b.HasIndex("QualitativeResultId");

                    b.HasIndex("QuantitativeInspectionMappingId");

                    b.ToTable("Production_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AnalyzedBy")
                        .HasColumnType("text");

                    b.Property<string>("BMRLoc")
                        .HasColumnType("text");

                    b.Property<string>("BMRNo")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("BatchNo")
                        .HasColumnType("text");

                    b.Property<string>("CardCode")
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .HasColumnType("text");

                    b.Property<double?>("CompletedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocEntry")
                        .HasColumnType("text");

                    b.Property<string>("DocNo")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("InspectionQuantity")
                        .HasColumnType("double precision");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBarcodeGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPerformed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPostedToSap")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<int?>("LineNo")
                        .HasColumnType("integer");

                    b.Property<string>("LineStatus")
                        .HasColumnType("text");

                    b.Property<double?>("OpenQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("OperatedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("OverallStatus")
                        .HasColumnType("boolean");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("QcLotNo")
                        .HasColumnType("text");

                    b.Property<double?>("ReceiveQuantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("RejectedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportNextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SampleQuantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("SapQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UoM")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatGroup")
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<string>("Warehouse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Purchase_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InspectionQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSamplePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("QcId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcId");

                    b.ToTable("Purchase_QC_Sample");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuantitativeResultPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QcSampleId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("QuantitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<double?>("QuantitativeResult")
                        .HasColumnType("double precision");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QcSampleId");

                    b.HasIndex("QualitativeInspectionMappingId");

                    b.HasIndex("QualitativeResultId");

                    b.HasIndex("QuantitativeInspectionMappingId");

                    b.ToTable("Purchase_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemInspectionCardId")
                        .HasColumnType("text");

                    b.Property<string>("Qualitative_ResultId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemInspectionCardId")
                        .IsUnique();

                    b.HasIndex("Qualitative_ResultId");

                    b.ToTable("Qualitative_Inspection");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection_Mapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("QualitativeInspectionId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("QualitativeInspectionId");

                    b.ToTable("Qualitative_Inspection_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Result", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ResultDescription")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Qualitative_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Result_Pass_Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("QualitativeInspectionMappingId")
                        .HasColumnType("text");

                    b.Property<string>("QualitativeResultId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QualitativeInspectionMappingId");

                    b.HasIndex("QualitativeResultId");

                    b.ToTable("Qualitative_Result_Pass_Status");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemInspectionCardId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemInspectionCardId")
                        .IsUnique();

                    b.ToTable("Quantitative_Inspection");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection_Mapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<double?>("Max")
                        .HasColumnType("double precision");

                    b.Property<double?>("Min")
                        .HasColumnType("double precision");

                    b.Property<string>("QuantitativeInspectionId")
                        .HasColumnType("text");

                    b.Property<double?>("Target")
                        .HasColumnType("double precision");

                    b.Property<string>("UoMId")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("QuantitativeInspectionId");

                    b.HasIndex("UoMId");

                    b.ToTable("Quantitative_Inspection_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Sampling_Range", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CriticalDefects")
                        .HasColumnType("double precision");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemSampleId")
                        .HasColumnType("text");

                    b.Property<double?>("LotSizeMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("LotSizeMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("MajorDefects")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinorDefects")
                        .HasColumnType("double precision");

                    b.Property<double?>("SampleQty")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemSampleId");

                    b.ToTable("Sampling_Range");
                });

            modelBuilder.Entity("DM.DomainModels.Unit_Of_Measure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IntCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("DatabaseGenerated", "Identity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntCode"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("UoMcode")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Unit_Of_Measure");
                });

            modelBuilder.Entity("DM.DomainModels.Inspection_Characteristic_Mapping", b =>
                {
                    b.HasOne("DM.DomainModels.Inspection_Characteristic", "Inspection_Characteristic")
                        .WithMany("Inspection_Characteristic_Mappings")
                        .HasForeignKey("CharacteristicId");

                    b.HasOne("DM.DomainModels.Inspection_Card", "Inspection_Card")
                        .WithMany("Inspection_Characteristic_Mappings")
                        .HasForeignKey("InspectionCardId");

                    b.Navigation("Inspection_Card");

                    b.Navigation("Inspection_Characteristic");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Inspection_Card", b =>
                {
                    b.HasOne("DM.DomainModels.Inspection_Card", "Inspection_Card")
                        .WithMany("Item_Inspection_Cards")
                        .HasForeignKey("InspectionCardId");

                    b.HasOne("DM.DomainModels.Item", "Item")
                        .WithMany("Item_Inspection_Cards")
                        .HasForeignKey("ItemId");

                    b.Navigation("Inspection_Card");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Sample", b =>
                {
                    b.HasOne("DM.DomainModels.Item", "Item")
                        .WithOne("Item_Sample")
                        .HasForeignKey("DM.DomainModels.Item_Sample", "ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Post_Sap", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA", "Production_QA")
                        .WithMany("Log_Post_Saps")
                        .HasForeignKey("QId");

                    b.HasOne("DM.DomainModels.Production_QC", "Production_QC")
                        .WithMany("Log_Post_Saps")
                        .HasForeignKey("QId");

                    b.HasOne("DM.DomainModels.Purchase_QC", "Purchase_QC")
                        .WithMany("Log_Post_Saps")
                        .HasForeignKey("QId");

                    b.Navigation("Production_QA");

                    b.Navigation("Production_QC");

                    b.Navigation("Purchase_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QA_Cavity", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA_Cavity", "Production_QA_Cavity")
                        .WithMany("Log_Production_QA_Cavities")
                        .HasForeignKey("CavityId");

                    b.Navigation("Production_QA_Cavity");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QA_Cavity_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA_Cavity_Sample_Result", "Production_QA_Cavity_Sample_Result")
                        .WithMany("Log_Production_QA_Cavity_Sample_Results")
                        .HasForeignKey("QaCavitySampleResultId");

                    b.Navigation("Production_QA_Cavity_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Production_QC_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QC_Sample_Result", "Production_QC_Sample_Result")
                        .WithMany("Log_Production_QC_Sample_Results")
                        .HasForeignKey("QcSampleResultId");

                    b.Navigation("Production_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Purchase_QC_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Purchase_QC_Sample_Result", "Purchase_QC_Sample_Result")
                        .WithMany("Log_Purchase_QC_Sample_Results")
                        .HasForeignKey("QcSampleResultId");

                    b.Navigation("Purchase_QC_Sample_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Log_Sampling_Range", b =>
                {
                    b.HasOne("DM.DomainModels.Sampling_Range", "SamplingRange")
                        .WithMany("Log_Sampling_Ranges")
                        .HasForeignKey("SamplingRangeId");

                    b.Navigation("SamplingRange");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA", b =>
                {
                    b.HasOne("DM.DomainModels.Item", "Item")
                        .WithMany("Production_QA")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA", "Production_QA")
                        .WithMany("Production_QA_Cavities")
                        .HasForeignKey("QaId");

                    b.Navigation("Production_QA");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA_Cavity", "Production_QA_Cavity")
                        .WithMany("Production_QA_Cavity_Samples")
                        .HasForeignKey("CavityId");

                    b.Navigation("Production_QA_Cavity");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QA_Cavity_Sample", "Production_QA_Cavity_Sample")
                        .WithMany("Production_QA_Cavity_Sample_Results")
                        .HasForeignKey("QaCavitySampleId");

                    b.HasOne("DM.DomainModels.Qualitative_Inspection_Mapping", "Qualitative_Inspection_Mapping")
                        .WithMany("Production_QA_Cavity_Sample_Results")
                        .HasForeignKey("QualitativeInspectionMappingId");

                    b.HasOne("DM.DomainModels.Qualitative_Result", "Qualitative_Result")
                        .WithMany("Production_QA_Cavity_Sample_Results")
                        .HasForeignKey("QualitativeResultId");

                    b.HasOne("DM.DomainModels.Quantitative_Inspection_Mapping", "Quantitative_Inspection_Mapping")
                        .WithMany("Production_QA_Cavity_Sample_Results")
                        .HasForeignKey("QuantitativeInspectionMappingId");

                    b.Navigation("Production_QA_Cavity_Sample");

                    b.Navigation("Qualitative_Inspection_Mapping");

                    b.Navigation("Qualitative_Result");

                    b.Navigation("Quantitative_Inspection_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC", b =>
                {
                    b.HasOne("DM.DomainModels.Item", "Item")
                        .WithMany("Production_QC")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QC", "Production_QC")
                        .WithMany("Production_QC_Samples")
                        .HasForeignKey("QcId");

                    b.Navigation("Production_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Production_QC_Sample", "Production_QC_Sample")
                        .WithMany("Production_QC_Sample_Results")
                        .HasForeignKey("QcSampleId");

                    b.HasOne("DM.DomainModels.Qualitative_Inspection_Mapping", "Qualitative_Inspection_Mapping")
                        .WithMany("Production_QC_Sample_Results")
                        .HasForeignKey("QualitativeInspectionMappingId");

                    b.HasOne("DM.DomainModels.Qualitative_Result", "Qualitative_Result")
                        .WithMany("Production_QC_Sample_Results")
                        .HasForeignKey("QualitativeResultId");

                    b.HasOne("DM.DomainModels.Quantitative_Inspection_Mapping", "Quantitative_Inspection_Mapping")
                        .WithMany("Production_QC_Sample_Results")
                        .HasForeignKey("QuantitativeInspectionMappingId");

                    b.Navigation("Production_QC_Sample");

                    b.Navigation("Qualitative_Inspection_Mapping");

                    b.Navigation("Qualitative_Result");

                    b.Navigation("Quantitative_Inspection_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC", b =>
                {
                    b.HasOne("DM.DomainModels.Item", "Item")
                        .WithMany("Purchase_QC")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample", b =>
                {
                    b.HasOne("DM.DomainModels.Purchase_QC", "Purchase_QC")
                        .WithMany("Purchase_QC_Samples")
                        .HasForeignKey("QcId");

                    b.Navigation("Purchase_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample_Result", b =>
                {
                    b.HasOne("DM.DomainModels.Purchase_QC_Sample", "Purchase_QC_Sample")
                        .WithMany("Purchase_QC_Sample_Results")
                        .HasForeignKey("QcSampleId");

                    b.HasOne("DM.DomainModels.Qualitative_Inspection_Mapping", "Qualitative_Inspection_Mapping")
                        .WithMany("Purchase_QC_Sample_Results")
                        .HasForeignKey("QualitativeInspectionMappingId");

                    b.HasOne("DM.DomainModels.Qualitative_Result", "Qualitative_Result")
                        .WithMany("Purchase_QC_Sample_Results")
                        .HasForeignKey("QualitativeResultId");

                    b.HasOne("DM.DomainModels.Quantitative_Inspection_Mapping", "Quantitative_Inspection_Mapping")
                        .WithMany("Purchase_QC_Sample_Results")
                        .HasForeignKey("QuantitativeInspectionMappingId");

                    b.Navigation("Purchase_QC_Sample");

                    b.Navigation("Qualitative_Inspection_Mapping");

                    b.Navigation("Qualitative_Result");

                    b.Navigation("Quantitative_Inspection_Mapping");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection", b =>
                {
                    b.HasOne("DM.DomainModels.Item_Inspection_Card", "Item_Inspection_Card")
                        .WithOne("Qualitative_Inspection")
                        .HasForeignKey("DM.DomainModels.Qualitative_Inspection", "ItemInspectionCardId");

                    b.HasOne("DM.DomainModels.Qualitative_Result", null)
                        .WithMany("Qualitative_Inspections")
                        .HasForeignKey("Qualitative_ResultId");

                    b.Navigation("Item_Inspection_Card");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection_Mapping", b =>
                {
                    b.HasOne("DM.DomainModels.Inspection_Characteristic", "Inspection_Characteristic")
                        .WithMany("Qualitative_Inspection_Mappings")
                        .HasForeignKey("CharacteristicId");

                    b.HasOne("DM.DomainModels.Qualitative_Inspection", "Qualitative_Inspection")
                        .WithMany("Qualitative_Inspection_Mappings")
                        .HasForeignKey("QualitativeInspectionId");

                    b.Navigation("Inspection_Characteristic");

                    b.Navigation("Qualitative_Inspection");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Result_Pass_Status", b =>
                {
                    b.HasOne("DM.DomainModels.Qualitative_Inspection_Mapping", "Qualitative_Inspection_Mapping")
                        .WithMany("Qualitative_Result_Pass_Statuses")
                        .HasForeignKey("QualitativeInspectionMappingId");

                    b.HasOne("DM.DomainModels.Qualitative_Result", "Qualitative_Result")
                        .WithMany("Qualitative_Result_Pass_Statuses")
                        .HasForeignKey("QualitativeResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Qualitative_Inspection_Mapping");

                    b.Navigation("Qualitative_Result");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection", b =>
                {
                    b.HasOne("DM.DomainModels.Item_Inspection_Card", "Item_Inspection_Card")
                        .WithOne("Quantitative_Inspection")
                        .HasForeignKey("DM.DomainModels.Quantitative_Inspection", "ItemInspectionCardId");

                    b.Navigation("Item_Inspection_Card");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection_Mapping", b =>
                {
                    b.HasOne("DM.DomainModels.Inspection_Characteristic", "Inspection_Characteristic")
                        .WithMany("Quantitative_Inspection_Mappings")
                        .HasForeignKey("CharacteristicId");

                    b.HasOne("DM.DomainModels.Quantitative_Inspection", "Quantitative_Inspection")
                        .WithMany("Quantitative_Inspection_Mappings")
                        .HasForeignKey("QuantitativeInspectionId");

                    b.HasOne("DM.DomainModels.Unit_Of_Measure", "Unit_Of_Measure")
                        .WithMany("Quantitative_Inspection_Mappings")
                        .HasForeignKey("UoMId");

                    b.Navigation("Inspection_Characteristic");

                    b.Navigation("Quantitative_Inspection");

                    b.Navigation("Unit_Of_Measure");
                });

            modelBuilder.Entity("DM.DomainModels.Sampling_Range", b =>
                {
                    b.HasOne("DM.DomainModels.Item_Sample", "Item_Sample")
                        .WithMany("Sampling_Ranges")
                        .HasForeignKey("ItemSampleId");

                    b.Navigation("Item_Sample");
                });

            modelBuilder.Entity("DM.DomainModels.Inspection_Card", b =>
                {
                    b.Navigation("Inspection_Characteristic_Mappings");

                    b.Navigation("Item_Inspection_Cards");
                });

            modelBuilder.Entity("DM.DomainModels.Inspection_Characteristic", b =>
                {
                    b.Navigation("Inspection_Characteristic_Mappings");

                    b.Navigation("Qualitative_Inspection_Mappings");

                    b.Navigation("Quantitative_Inspection_Mappings");
                });

            modelBuilder.Entity("DM.DomainModels.Item", b =>
                {
                    b.Navigation("Item_Inspection_Cards");

                    b.Navigation("Item_Sample");

                    b.Navigation("Production_QA");

                    b.Navigation("Production_QC");

                    b.Navigation("Purchase_QC");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Inspection_Card", b =>
                {
                    b.Navigation("Qualitative_Inspection");

                    b.Navigation("Quantitative_Inspection");
                });

            modelBuilder.Entity("DM.DomainModels.Item_Sample", b =>
                {
                    b.Navigation("Sampling_Ranges");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA", b =>
                {
                    b.Navigation("Log_Post_Saps");

                    b.Navigation("Production_QA_Cavities");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity", b =>
                {
                    b.Navigation("Log_Production_QA_Cavities");

                    b.Navigation("Production_QA_Cavity_Samples");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample", b =>
                {
                    b.Navigation("Production_QA_Cavity_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QA_Cavity_Sample_Result", b =>
                {
                    b.Navigation("Log_Production_QA_Cavity_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC", b =>
                {
                    b.Navigation("Log_Post_Saps");

                    b.Navigation("Production_QC_Samples");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample", b =>
                {
                    b.Navigation("Production_QC_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Production_QC_Sample_Result", b =>
                {
                    b.Navigation("Log_Production_QC_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC", b =>
                {
                    b.Navigation("Log_Post_Saps");

                    b.Navigation("Purchase_QC_Samples");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample", b =>
                {
                    b.Navigation("Purchase_QC_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Purchase_QC_Sample_Result", b =>
                {
                    b.Navigation("Log_Purchase_QC_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection", b =>
                {
                    b.Navigation("Qualitative_Inspection_Mappings");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Inspection_Mapping", b =>
                {
                    b.Navigation("Production_QA_Cavity_Sample_Results");

                    b.Navigation("Production_QC_Sample_Results");

                    b.Navigation("Purchase_QC_Sample_Results");

                    b.Navigation("Qualitative_Result_Pass_Statuses");
                });

            modelBuilder.Entity("DM.DomainModels.Qualitative_Result", b =>
                {
                    b.Navigation("Production_QA_Cavity_Sample_Results");

                    b.Navigation("Production_QC_Sample_Results");

                    b.Navigation("Purchase_QC_Sample_Results");

                    b.Navigation("Qualitative_Inspections");

                    b.Navigation("Qualitative_Result_Pass_Statuses");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection", b =>
                {
                    b.Navigation("Quantitative_Inspection_Mappings");
                });

            modelBuilder.Entity("DM.DomainModels.Quantitative_Inspection_Mapping", b =>
                {
                    b.Navigation("Production_QA_Cavity_Sample_Results");

                    b.Navigation("Production_QC_Sample_Results");

                    b.Navigation("Purchase_QC_Sample_Results");
                });

            modelBuilder.Entity("DM.DomainModels.Sampling_Range", b =>
                {
                    b.Navigation("Log_Sampling_Ranges");
                });

            modelBuilder.Entity("DM.DomainModels.Unit_Of_Measure", b =>
                {
                    b.Navigation("Quantitative_Inspection_Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
